### ISSUE TITLE
Error enabling module

### ISSUE THREAD

**Issue by iznaut** [susom/redcap-em-shazam#15]
I tried to upgrade to Shazam v1.2.1 and it gave me an error:

```
An error occurred while enabling the module: <div class='red' style='max-width:700px;'>
							<b>ERROR:</b> There is an error in the REDCap plugin that you are currently using. Please contact
	this plugin's developer and send them the error info listed below so that they may fix this issue.
	If you do not know who the developer is for this plugin, then notify your REDCap administrator about this issue.<br><br>
							<b>Error message:</b> Uncaught Error: Call to undefined function ExternalModules\isCompatibleFormatCorrect() in /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php:1487
Stack trace:
#0 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php(517): ExternalModules\ExternalModules::isCompatibleWithREDCapPHP('shazam', 'v1.2.1')
#1 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php(562): ExternalModules\ExternalModules::enableForProject('shazam', 'v1.2.1', NULL)
#2 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php(568): ExternalModules\ExternalModules::enable('shazam', 'v1.2.1')
#3 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/manager/ajax/enable-module.php(44): ExternalModules\ExternalModules::enableAndCatchExceptions('shazam', 'v1.2.1')
#4 {main}
  thrown <br>
							<b>File:</b> /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php <br>
							<b>Line:</b> 1487
						</div>
```

**Comment by iznaut** [comment]
It looks like maybe I just wasn't supposed to be able to download it on REDCap v8.6.5?

```
"compatibility": {
    "php-version-min": "5.4.0",
    "redcap-version-min": "8.7.0"
  }
```

**Comment by 123andy** [comment]
Hi Eric,

That is correct - the latest version for < 8.7 is 1.19.

-A


On Aug 29, 2018, at 11:53 AM, Eric Neuhaus <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like maybe I just wasn't supposed to be able to download it on REDCap v8.6.5?

"compatibility": {
    "php-version-min": "5.4.0",
    "redcap-version-min": "8.7.0"
  }

**Comment by 123andy** [comment]
Rob fixed a config issue on the repo and you should be able to download version 1.1.9 now.  Please try again.
